export const similarWords = [
  ["seal", "meal", "deal", "teal"],
  ["make", "fake", "take", "wake", "cake", "bake", "rake"],
  ["fun", "sun", "run", "bun"],
  ["par", "car", "far", "bar"],
  ["their", "there", "share", "where"],
  ["wear", "tear", "fear", "near", "dear", "rear", "pear"],
  ["chair", "stair", "fair", "hair"],
  ["bay", "day", "pay", "fay", "may"],
  ["stay", "play", "slay", "tray"],
  ["date", "late", "gate", "rate", "hate", "mate"],
  ["rare", "dare", "fare", "care"],
  ["viable", "table", "cable", "fable"],
  ["tone", "phone", "hone", "cone", "none", "done"],
  ["snow", "show", "crow", "brow", "know"],
  ["slow", "glow", "flow", "blow"],
  ["toe", "woe", "foe", "doe"],
  ["now", "how", "wow", "low", "vow"],
  ["tall", "call", "ball", "fall"],
  ["might", "sight", "night", "right", "tight"],
  ["kite", "rite", "site", "bite"],
  ["rice", "nice", "dice", "vice", "mice"],
  ["sense", "tense", "dense", "fence"],
  ["fell", "well", "tell", "bell", "hell", "sell", "yell"],
  ["weigh", "sleigh", "eight", "weight"],
  ["day", "hay", "may", "pay"],
  ["page", "wage", "rage", "cage"],
  ["bee", "see", "sea", "tea"],
  ["beach", "teach", "reach", "peach", "leach"],
  ["sane", "lane", "cane", "pane"],
  ["look", "cook", "book", "took"],
  ["tiny", "silly", "very", "lazy"],
  ["week", "geek", "reek", "meet", "meat"],
  ["spout", "trout", "shout", "trout", "about"],
  ["like", "bike", "pike", "dike"],
  ["free", "three", "agree", "tree"],
  ["could", "would", "mould", "should"],
  ["grain", "chain", "brain", "drain", "plain", "train"],
  ["gain", "pain", "rain", "main"],
  ["creep", "sheep", "sweep", "sleep", "steep", "cheep"],
  ["keep", "peep", "weep", "jeep", "beep"]
];
